### ISSUE TITLE
Please review int_to_bytes, bytes_to_int, lemmaBytesToIntIsTheInverseOfIntToBytes, lemmaIntToBytesIsTheInverseOfBytesToInt in beacon/helpers/Math.dfy

### ISSUE THREAD

**Issue by saltiniroberto** [PegaSysEng/eth2.0-dafny#19]
Please review 

- int_to_bytes, 
- bytes_to_int, 
- lemmaBytesToIntIsTheInverseOfIntToBytes, 
- lemmaIntToBytesIsTheInverseOfBytesToInt 

in 
`beacon/helpers/Math.dfy`

**Comment by franck44** [comment]
@saltiniroberto 
1. I suggest moving the int_to_bytes/bytes_to_ints to the BytesAndBits.dfy file (ssz).
This is where the counterpart functions for uint8 are located.

2. The proof of the second lemma can be simplified using the first one. Here is the simplified version:
```
lemma foo(s: bytes)
    requires bytes_to_int.requires(s)
    ensures int_to_bytes(bytes_to_int(s),|s| as uint64) == s 
    {
        calc {
            bytes_to_int(int_to_bytes(bytes_to_int(s),|s| as uint64));
            ==
            bytes_to_int(s);
        }
    }
```

**Comment by saltiniroberto** [comment]
Thanks for the review @franck44  and for pointing out a simpler proof the second lemma.

On the first point, however, I would prefer to leave `int_to_bytes` and `bytes_to_int` where they are for the moment as they are technically part of the beacon-chain spec, not of the SSZ spec.
Also, by keeping the current organisation is very straightforward to check that, for example, all the functions of Math helper section of the beacon chain specification have been verified.

**Comment by franck44** [comment]
[DONE]
