### ISSUE TITLE
Make the behaviour of int_to_bytes and bytes_to_int in Math.dfy dependent on the ENDIANNESS constant

### ISSUE THREAD

**Issue by saltiniroberto** [PegaSysEng/eth2.0-dafny#20]
The Eth2 .md spec prescribes that the behaviour of `int_to_bytes` and `bytes_to_int` should be dependent on the value of the `ENDIANNESS` constant.

In the current Dafny specification, little endianness is hardcoded for both functions.

To note that little endianness is also hardcoded for both functions in the Eth2 K-Spec.

**Comment by franck44** [comment]
I think little endian is the choice for the spec, and there is no consideration to move to big endianness. 
Am I missing something?

**Comment by saltiniroberto** [comment]
> I think little endian is the choice for the spec, and there is no consideration to move to big endianness.

You may be right, it is probably inconceivable that the endianness may be changed now.

However, the [Eth2 spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#int_to_bytes) still specifies that `int_to_bytes` and  `bytes_to_int` should be dependent on the value of `ENDIANNESS`.
![image](https://user-images.githubusercontent.com/38655434/81244807-b23ab300-9056-11ea-8647-80610a25b0c1.png)

**Comment by franck44** [comment]
Closing this as seems to be resolved.
